// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MutluSporSalonu.Models;

#nullable disable

namespace MutluSporSalonu.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20251217195248_ilk_migration")]
    partial class ilk_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AntrenorHizmet", b =>
                {
                    b.Property<int>("AntrenorlerAntrenorID")
                        .HasColumnType("int");

                    b.Property<int>("HizmetlerHizmetID")
                        .HasColumnType("int");

                    b.HasKey("AntrenorlerAntrenorID", "HizmetlerHizmetID");

                    b.HasIndex("HizmetlerHizmetID");

                    b.ToTable("AntrenorHizmet");
                });

            modelBuilder.Entity("MutluSporSalonu.Models.Antrenor", b =>
                {
                    b.Property<int>("AntrenorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AntrenorID"));

                    b.Property<string>("AntrenorAdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AntrenorEposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("AntrenorMusaitlikBaslangic")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("AntrenorMusaitlikBitis")
                        .HasColumnType("time");

                    b.Property<string>("AntrenorTelefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AntrenorUzmanlikAlanlari")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("SalonId")
                        .HasColumnType("int");

                    b.Property<int?>("SporSalonuSalonID")
                        .HasColumnType("int");

                    b.HasKey("AntrenorID");

                    b.HasIndex("SporSalonuSalonID");

                    b.ToTable("Antrenorler");
                });

            modelBuilder.Entity("MutluSporSalonu.Models.Hizmet", b =>
                {
                    b.Property<int>("HizmetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HizmetID"));

                    b.Property<string>("HizmetAciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("HizmetAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("HizmetSureDakika")
                        .HasColumnType("int");

                    b.Property<decimal>("HizmetUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalonID")
                        .HasColumnType("int");

                    b.Property<int?>("SporSalonuSalonID")
                        .HasColumnType("int");

                    b.HasKey("HizmetID");

                    b.HasIndex("SporSalonuSalonID");

                    b.ToTable("Hizmetler");
                });

            modelBuilder.Entity("MutluSporSalonu.Models.Randevu", b =>
                {
                    b.Property<int>("RandevuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RandevuID"));

                    b.Property<int>("AntrenorID")
                        .HasColumnType("int");

                    b.Property<int>("HizmetID")
                        .HasColumnType("int");

                    b.Property<string>("RandevuAciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("RandevuBaslangicSaati")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("RandevuBitisSaati")
                        .HasColumnType("time");

                    b.Property<DateTime>("RandevuOlusturulmaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RandevuOnaylandiMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("RandevuTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("RandevuUcret")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SalonID")
                        .HasColumnType("int");

                    b.Property<int?>("SporSalonuSalonID")
                        .HasColumnType("int");

                    b.Property<int>("UyeID")
                        .HasColumnType("int");

                    b.HasKey("RandevuID");

                    b.HasIndex("AntrenorID");

                    b.HasIndex("HizmetID");

                    b.HasIndex("SporSalonuSalonID");

                    b.HasIndex("UyeID");

                    b.ToTable("Randevular");
                });

            modelBuilder.Entity("MutluSporSalonu.Models.SporSalonu", b =>
                {
                    b.Property<int>("SalonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalonID"));

                    b.Property<string>("SalonAciklama")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<TimeSpan>("SalonAcilisSaati")
                        .HasColumnType("time");

                    b.Property<string>("SalonAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SalonAdres")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<TimeSpan>("SalonKapanisSaati")
                        .HasColumnType("time");

                    b.HasKey("SalonID");

                    b.ToTable("Salonlar");
                });

            modelBuilder.Entity("MutluSporSalonu.Models.Uye", b =>
                {
                    b.Property<int>("UyeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UyeID"));

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("UyeAdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UyeEposta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UyeSifre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UyeTelefon")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UyeID");

                    b.ToTable("Uyeler");
                });

            modelBuilder.Entity("AntrenorHizmet", b =>
                {
                    b.HasOne("MutluSporSalonu.Models.Antrenor", null)
                        .WithMany()
                        .HasForeignKey("AntrenorlerAntrenorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MutluSporSalonu.Models.Hizmet", null)
                        .WithMany()
                        .HasForeignKey("HizmetlerHizmetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MutluSporSalonu.Models.Antrenor", b =>
                {
                    b.HasOne("MutluSporSalonu.Models.SporSalonu", "SporSalonu")
                        .WithMany("Antrenorler")
                        .HasForeignKey("SporSalonuSalonID");

                    b.Navigation("SporSalonu");
                });

            modelBuilder.Entity("MutluSporSalonu.Models.Hizmet", b =>
                {
                    b.HasOne("MutluSporSalonu.Models.SporSalonu", "SporSalonu")
                        .WithMany("Hizmetler")
                        .HasForeignKey("SporSalonuSalonID");

                    b.Navigation("SporSalonu");
                });

            modelBuilder.Entity("MutluSporSalonu.Models.Randevu", b =>
                {
                    b.HasOne("MutluSporSalonu.Models.Antrenor", "Antrenor")
                        .WithMany("Randevular")
                        .HasForeignKey("AntrenorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MutluSporSalonu.Models.Hizmet", "Hizmet")
                        .WithMany()
                        .HasForeignKey("HizmetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MutluSporSalonu.Models.SporSalonu", "SporSalonu")
                        .WithMany()
                        .HasForeignKey("SporSalonuSalonID");

                    b.HasOne("MutluSporSalonu.Models.Uye", "Uye")
                        .WithMany("Randevular")
                        .HasForeignKey("UyeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Antrenor");

                    b.Navigation("Hizmet");

                    b.Navigation("SporSalonu");

                    b.Navigation("Uye");
                });

            modelBuilder.Entity("MutluSporSalonu.Models.Antrenor", b =>
                {
                    b.Navigation("Randevular");
                });

            modelBuilder.Entity("MutluSporSalonu.Models.SporSalonu", b =>
                {
                    b.Navigation("Antrenorler");

                    b.Navigation("Hizmetler");
                });

            modelBuilder.Entity("MutluSporSalonu.Models.Uye", b =>
                {
                    b.Navigation("Randevular");
                });
#pragma warning restore 612, 618
        }
    }
}
